### PR TITLE
Refactor and move to nixosModules

### PR DESCRIPTION
**Pull request by DerDennisOP**
As spoken in #13 

Help is very welcome :).

### CODE REVIEW

**Comment by DerDennisOP** [comment]
Usually splitting up would be the right thing here. But I somehow ended up changing the entire project, so splitting up changes in 61 files would be a lot of work for me. I also did some formatting, which makes reviewing very hard, hopefully you are able to review it anyway.

**Comment by AkechiShiro** [comment]
This PR did break some stuff that has been fixed, as there was no tag 24.05, there shouldn't have been any full replace.

@DerDennisOP please tag me from now on in any change you would like to PR, I'll also attempt to leave a review and retest before a merge happens, as an extra pair of eyes as @D3vil0p3r might not have the time to cover large PRs.

**Comment by D3vil0p3r** [comment]
@DerDennisOP one question: in https://github.com/Athena-OS/athena-nix/blob/main/nixos/home-manager/shells/bash/default.nix there is the content of `.bashrc` that was already specifying in https://github.com/Athena-OS/athena-nix/blob/main/nixos/home-manager/shells/bash/bashrc

What do we need to remove?

**Comment by DerDennisOP** [comment]
@D3vil0p3r I would remove the string text in the default.nix file. It makes the nix code better readable, and the bashrc would then have the bashrc content. Currently both ways are in use, so you might remove the text parts that are overlaying with the bashrc file content.

**Pull request merged**
